apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\mikie\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: redis-node-1
  name: redis-node-1
spec:
  ports:
    - name: "7001"
      port: 7001
      targetPort: 7000
  selector:
    io.kompose.service: redis-node-1
